import { getDefaultClassNames } from "./getDefaultClassNames";

test("should return the default classnames", () => {
  expect(getDefaultClassNames()).toStrictEqual({
    button_next: "rdp-button_next",
    button_previous: "rdp-button_previous",
    root: "rdp-root",
    caption_label: "rdp-caption_label",
    chevron: "rdp-chevron",
    day: "rdp-day",
    day_button: "rdp-day_button",
    disabled: "rdp-disabled",
    dropdowns: "rdp-dropdowns",
    dropdown_root: "rdp-dropdown_root",
    dropdown: "rdp-dropdown",
    focused: "rdp-focused",
    footer: "rdp-footer",
    hidden: "rdp-hidden",
    month_caption: "rdp-month_caption",
    month_grid: "rdp-month_grid",
    month: "rdp-month",
    weeks: "rdp-weeks",
    months_dropdown: "rdp-months_dropdown",
    months: "rdp-months",
    nav: "rdp-nav",
    outside: "rdp-outside",
    range_end: "rdp-range_end",
    range_middle: "rdp-range_middle",
    range_start: "rdp-range_start",
    selected: "rdp-selected",
    today: "rdp-today",
    week_number: "rdp-week_number",
    week_number_header: "rdp-week_number_header",
    week: "rdp-week",
    weekday: "rdp-weekday",
    weekdays: "rdp-weekdays",
    years_dropdown: "rdp-years_dropdown",
    caption_next_in: "rdp-caption_next_in",
    caption_prev_in: "rdp-caption_prev_in",
    weeks_next_in: "rdp-weeks_next_in",
    weeks_prev_in: "rdp-weeks_prev_in",
    caption_next_out: "rdp-caption_next_out",
    caption_prev_out: "rdp-caption_prev_out",
    weeks_next_out: "rdp-weeks_next_out",
    weeks_prev_out: "rdp-weeks_prev_out"
  });
});
